version: "3.9"

services:
  funnow-api-server:
    container_name: funnow-api-server
    build: .
    env_file:
      - env/local.env
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - funnow

  redis:
    container_name: funnow-redis
    image: bitnami/redis:6.2.7
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - funnow

networks:
  funnow:
